### ISSUE TITLE
Main window freezes up when AutoMode starts

### ISSUE THREAD

**Issue by ArielMAJ** [Leah9/screengrab#23]
Tkinter has this thing in which when you do operations in loops (or that are long in general and don't involve their widgets much) the window looks frozen up. I thought it would happen with time.sleep, but I'm actually noticing this when AutoMode is running.

Here are some options to solve that:
1. Hide the window right before the loop and restore it after it. (probably the best and certainly the easiest option)
2. Start the image capturing process in a new thread (multiprocessing) and disable all buttons while capturing the screen.

Which would you prefer, @Leah9?

**Comment by Leah9** [comment]
Number one sounds good for now, maybe number two a feature in the future ?

**Comment by ArielMAJ** [comment]
Yeah, number one is just two lines of code. Number two is something i have implemented before and could try to port it to this project if you're interested in that. 

But I'm also not sure if it would make much sense to have these two options. It would need a checkbox to switch between them in that case. This would align with #26 though.

What do you say?

**Comment by Leah9** [comment]
I will push what i have done to add the checkbox but i cant get the flippin thing working :(

If you can fix it would be amazing so i can see how it is meant to work ?

Honestly thought i was better than this :/

**Comment by ArielMAJ** [comment]
Sure thing. Dw it always happens. Everyone goes through that. I also often have times I can't find anywhere the solution to some specific problems. That's life hehe
I'll see into it after i finish up something here.
