### ISSUE TITLE
Images in the repository are overwritten when restarting the program (it restarts the counter).

### ISSUE THREAD

**Issue by ArielMAJ** [Leah9/screengrab#24]
TODO: Use len(glob(img*.png))

I'll probably implement this later

**Comment by Leah9** [comment]
Maybe a warning that there are existing images that will be over-written. Option to delete them, overwrite, or add to the folder starting at the next logical number ?

**Comment by ArielMAJ** [comment]
That's a good idea. From what I thought up here, we could either:
1. Add a messagebox.askquestion and either delete the old ones or continue from the next number; or
2. Use messagebox.askyesnocancel so we get the third button for overwritting (but the selected answers might not be too intuitive and lead to user mistakes); or
3. Write a new customized toplevel and create our own buttons (would be more complex).

Which would you prefer?

**Comment by ArielMAJ** [comment]
I've been thinking about this and I feel like having that window I suggested above pop up every time the app is opened might become annoying pretty fast. 

<hr>

A direct easy solution I've been thinking was instead of enumerating the images:
- [x] Save the images with a timestamp (instantly guarantees unique names); 

<hr>

I also have been thinking about trying something a bit more complex but somewhat more organized for the user, such as:
- [ ] Having a default subfolder in "img" for single captures.
- [ ] Starting a new subfolder for every time the user starts AutoMode.
     - [ ] In the AutoMode pop up window, together with the selected button to press, the user could also select the folder to add the images too (a list of existing subfolders in imgs and "New" by default).
- [ ] Create PDF would open a pop up window to choose the folder to make the PDFs from (defaults most recent folder).

<hr>

What do you say? Would you like to implement any of the above suggestions?
