### ISSUE TITLE
Add icon to app.

### ISSUE THREAD

**Issue by ArielMAJ** [Leah9/screengrab#40]
Having an iconname.ico file would be really interesting so the app would show it on the top-left corner. We could also use it to make a pretty shortcut. Anything you like and that's free to use should do it.

e.g.
<img width="123" alt="image" src="https://user-images.githubusercontent.com/69123486/169581291-ec15dc9e-5421-4e46-b60a-4347c596f09a.png">

**Comment by Leah9** [comment]
Resolved with 1569b75d3bd854fde8e79e1b3fada36a6c5e2c90
#
