### ISSUE TITLE
Add option to change key press to different value when auto is used

### ISSUE THREAD

**Issue by Leah9** [Leah9/screengrab#5]
Currently the "Auto" mode itterates through the number of pages and goes to the next page using the down arrow. 
This may not work for all cases.
An option should be added to the GUI to allow using different keys presses or combinations or mouse input.

**Comment by ArielMAJ** [comment]
I'm working on this.

**Comment by ArielMAJ** [comment]
I'm implementing something similar to the old pop up window where the user pressed enter and it started doing its thing. But it's a custom window instead where the user would also have a dropdown box so they can change the default keypress.
We can still add the time.sleep() call after the user presses ok so they would have time to prepare for the screen shots.
